### ISSUE TITLE
redshift  - import do  DATETIME, copy options

### ISSUE THREAD

**Issue by Halama** [keboola/php-db-import#15]
Asi by ale měly být volitelné zvenčí?

`NULL AS 'NULL', ACCEPTANYDATE, TRUNCATECOLUMNS`

**Comment by ondrejhlavacek** [comment]
Nikdo to reálně nepoužívá (na jednu výjimku) a zvenčí nevíš, jestli to máš specifikovat nebo ne (nevíš, jestli to pojede přes S3 nebo interně).

**Comment by Halama** [comment]
aby to neovlivnilo stávající loady, bude to možné specifikovat přes options pro import.
