### ISSUE TITLE
Snowflake incremental import with PK - convert empty values to null

### ISSUE THREAD

**Issue by ErikZigo** [keboola/php-db-import#35]
Nasel jsem chybu v metode
`Keboola\Db\Import\Snowflake\ImportBase::insertOrUpdateTargetTable`
pri  incrementalnim zapisu do tabulky s primarnim klicem

Pri [aktualizaci existujicich zaznamu](https://github.com/keboola/php-db-import/blob/master/src/Snowflake/ImportBase.php#L192) se ignoruje nastaveni `$convertEmptyValuesToNull` . Aplikuje se pouze pri [vkladani novych zaznamu](https://github.com/keboola/php-db-import/blob/master/src/Snowflake/ImportBase.php#L255).

**Comment by ErikZigo** [comment]
Navic pokud tabulka muze obsahovat `NULL` hodnoty, tak pak je nefunkcni i [podminka](https://github.com/keboola/php-db-import/blob/master/src/Snowflake/ImportBase.php#L218) pro aktualizaci pouze zmenenych zaznamu.

Porovnavaji se tam zdrojova a cilova data. V tomhle pripade ale muze dojit k situaci `cokoliv != NULL`. To nikdy nevrati`true/false`, ale **vzdy NULL**. Takze zmeny se do cilove databaze nepromitnou!

**Comment by ErikZigo** [comment]
@Halama koukl bys na ten PR? Jestli to neni ko.otina? Diky

RS testy padaj kvuli starym credentials na travisu.
Moc nechapu proc failuje MySQL test. U me v dockeru to funguje.

**Comment by Halama** [comment]
Ty testy by mely prochazet vsechny.

**Comment by Halama** [comment]
Ten Redshift jsem nejspis asi zkurvil ja kdyz jsem tam mazal db, ten teda fixnu.

**Comment by ErikZigo** [comment]
https://travis-ci.org/keboola/php-db-import/builds/302491614

RS dava ze neexistuje databaze

**Comment by Halama** [comment]
Fixnu ted ty RS testy ale zkouknul bych to radsi az zitra rano.

**Comment by Halama** [comment]
Nastavil jsem nove RS credentials a restartnul to https://travis-ci.org/keboola/php-db-import/builds/302501478

**Comment by ErikZigo** [comment]
Zitrek asi v pohode. Me to neblokuje. Ja koukam ze stejny problem bude i u redshiftu. Tak na to delam taky test a fix.

**Comment by Halama** [comment]
ok super. Kdyztak prosim mrkni i na ty mysql testy proc failuji.

**Comment by Halama** [comment]
vypada to ze RS uz bezi.

**Comment by ErikZigo** [comment]
MySQL faily jsou zpusobeny novejsi verzi PhpUnitu. To nebude problem fixnout.

**Comment by Halama** [comment]
ok super, tak to prosim fixni asi v tomhle PR at je to zeleny :)
