### ISSUE TITLE
Snowflake - support more than 1000 slices

### ISSUE THREAD

**Issue by Halama** [keboola/php-db-import#39]
Aktuálně používáme v COPY commandu property `FILES` která má limit 1000.
Pokud má soubor více slices vracíme user error.

https://github.com/keboola/php-db-import/blob/3606e32659978b5a5151b8484fb1ec072cdb0071/src/Snowflake/CsvImportBase.php#L109

**Comment by Halama** [comment]
https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-table.html

**Comment by Halama** [comment]
Možná můžeme např. jenom rozsekat po tisících a volat COPY vícekrát po sobě.

**Comment by pivnicek** [comment]
Jo, vypada ze je to asi hard limit

![image](https://user-images.githubusercontent.com/569139/35626572-6e0f6456-0696-11e8-8f74-bce35d31f164.png)

**Comment by Halama** [comment]
yes it is

**Comment by Halama** [comment]
Trochu jsem se na to dival a klonil bych se asi k tomu to rozsekat prostě po 1000 filech a pro každou dávku pak volal samostatný `COPY` command. Vždy se importuje do staging tabulky takže nehrozí nekonzistence v případě importu jedné a failu druhé.

Další možností by bylo použít `PATTERN ` místo `FILES`  kvůli vynechání manifest souboru, je potřeba ale zajistit at to nevynechá nic jiného.

**Comment by ErikZigo** [comment]
Tohle by se melo vyresit i v KBC. Kde failne restore velke tabulky ze snapshotu https://github.com/keboola/connection/issues/1031

**Comment by Halama** [comment]
jo resim to kvuli kbc, tam se tohle pouziva pro importy i restore.

**Comment by Halama** [comment]
i z toho duvodu tech snapshotu by teda bylo dobry to fixnout, protoze snapshot ktery nejde restornout je trochu k nicemu :) I kdyz ted s releasem timz e travel snapshoty nebudou zas tolik potreba, resp. budou potreba jenom pokud si neco budes chtit odlit dlouhodobeji nez je retence projektu.

**Comment by ErikZigo** [comment]
Jo, nejak to issue v KBC vyhnilo :-)

**Comment by ondrejhlavacek** [comment]
+1

taky mě napadlo to nadávkovat po 1000, tím, že je to do stagingu, tak by to nemělo ničemu vadit.

**Comment by ondrejhlavacek** [comment]
https://keboola.slack.com/archives/C02C3GZUS/p1524212866000219
https://keboola.zendesk.com/agent/tickets/8292

**Comment by Halama** [comment]
On by asi ani ten PATTERN neměl být problém. Jenom bych to nedělal takhle https://github.com/keboola/transformation-bundle/blob/c474afec5a47a633f35b6cd4e9409088a21f144d/library/Keboola/Transformation/Backend/Snowflake.php#L348
protože v nějaké bizar situaci by tam klidně mohlo být více souborů které končí `manifest`.

Pokud by se ten regexp napsal tak ať to vynechá `$fileInfo["s3Path"]["key"].manifest` tak by to mělo být bezpečný.

**Comment by Halama** [comment]
I když vlastně ne. Teď říkáme že to importuje soubory které jsou zmíněné v manifestu. Ignorovat ho by mohl být BC break!

**Comment by Halama** [comment]
Problém může být s tím že potom ten JSON manifest může být velký https://github.com/keboola/connection/issues/867

**Comment by Halama** [comment]
Řešením by potom mohlo být deprekování manifestů a importovat prostě vše co leží pod daným prefixem. To ale může být až další krok.

**Comment by ondrejhlavacek** [comment]
Co kdyby se teda udělal druhej import, kterej by byl bez manifestu?

Mezitím jsem tady teda pracně vypotil regulár, kterej matchne všechny cesty kromě manifestu :-)

https://regex101.com/r/lTyF5h/1/

**Comment by Halama** [comment]
Tam hrozí ten BC break. To by se muselo nějak kontrolovaně zavést jako typ importu/souboru v SAPI.

**Comment by ondrejhlavacek** [comment]
No vždyť to jsem psal :-)

**Comment by Halama** [comment]
Jako že rovnou připravovat variantu bez manifestů?

**Comment by ondrejhlavacek** [comment]
Jj, než to nějak pytlíkovat po tisícovkách (tam to taky může na něco narazit?).

**Comment by ondrejhlavacek** [comment]
Ten manifest tam byl jen pro Redshift, ne?

**Comment by Halama** [comment]
Vzniklo to s Resdhiftem

**Comment by Halama** [comment]
Tak já na to založím asi issue v KBC

**Comment by ondrejhlavacek** [comment]
Bude to chtít ověřit, že to zvládne velký tisíce souborů, chceš s tím nějak pomoct?

**Comment by Halama** [comment]
Toho se nebojím, spíš bude potřeba pořádně promyslet, kompatibilitu, čeho všeho se to bude týkat atd.

**Comment by Halama** [comment]
Dovedu si představit že bude asi poměrně jednoduché zavést import kterému se řekne parametrem ať ignoruje manifest. 
Jak se ale kompletně zbavit manifestů, tzn. aby mohli existovat soubory bez nich zatím moc nevím. Všechny aktuální verze sapi klienta a další integrace by přestaly fungovat.

**Comment by ondrejhlavacek** [comment]
Pro Redshift ho stejně furt potřebujem.

**Comment by Halama** [comment]
Ono to vypadá že ani Redshift to nevyžaduje https://docs.aws.amazon.com/redshift/latest/dg/loading-data-files-using-manifest.html

**Comment by ondrejhlavacek** [comment]
Tak to by bylo super!

**Comment by Halama** [comment]
Jenže Redshift zas neumí ten PATTERN který je potřeba aby to ignorovalo ten manifest:( https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-source-s3.html

**Comment by Halama** [comment]
Začal jsem to sepisovat a vlastně moc nevím jak z toho ven.

**Comment by Halama** [comment]
U Redshiftu ale zas není tohle issue s velikostí nebo počtem slices, takže tam by se to mohlo chovat pořád stejně. I když je blbost mít parametr import `ignoreManifest` a ve skutečnosti ho používat pro RS.

**Comment by Halama** [comment]
To by možná šlo, tzn. byla by to feature files a ne importu. Import by se podle toho pak jenom zachoval a switchnul na jednu z verzí. 
File by měl nově flag `hasManifest`.

Tohodle řešení jsem se bál kvůli BC. Jde o to že ze stažením takového souboru by si neporadili aktuální verze SAPI klientů. Pokud bysme to začal nastavovat docker runner pro soubory které importuje to tabulek tak tam by asi problém nebyl. Nenapadá mě situace kdy by se soubor který byl jednou importovaný dále nějak zpracovával.

Otázka je co s tím pak dál pokud bysme chtěli kompletně přejít na files bez manifestů?

**Comment by Halama** [comment]
Shodou okolností se v pátek objevilo jiné issue s manifesty:) https://github.com/keboola/connection/issues/332#issuecomment-383366066

**Comment by ondrejhlavacek** [comment]
Jo aha, v tomhle je fígl, to mě nenapadlo. Bylo by super, kdyby starej SAPI klient dokázal říct, že ten soubor neumí stáhnout, ať použiješ novější. To by se tam mohlo nějak protlačit z API přinejhorším jako chyba na API?

**Comment by Halama** [comment]
No ale tím by to mohlo někomu rozbít integraci, taky vůbec nemusí používat naše klienty. Na naší straně bysme to ale poupgradovali v pohodě. Pak bysme viděli co zbylo.

Ještě přemýšlím jestli je nějaký důvod ty manifesty zachovat. Jediné co mě napadá je konzistence listování souborů v S3, to znovu ověřím.

**Comment by ondrejhlavacek** [comment]
Jo, to mohlo :-( Co myslíš tou konzistencí listování souborů v S3?

**Comment by Halama** [comment]
Napadlo mě  že bysme tam ten manifest prostě pro BC mohli nějak dogenerovávat. Blbý je že se přesně nedá určit okamžik kdy se to má stát:(

**Comment by Halama** [comment]
Tou konzistencí myslím jako že tam nasypeš najednou x souborů. A ihned potom zavoláš ten import který zavolá list nad tím prefixem v S3, tak jestli se nemůže stát že některý se tam třeba hned neobjeví.

**Comment by ondrejhlavacek** [comment]
Fabuluju - co kdyby měl manifest a soubory unikátní prefix? Potom by sis mohl šáhnout na manifest, kterej je mimo prefix/namespace souborů. Příklad

```
s3-bucket/folder/myfileimport/manifest
s3-bucket/folder/myfileimport/files/part0
s3-bucket/folder/myfileimport/files/part1
s3-bucket/folder/myfileimport/files/part2
```
Má to společnej prefix, v manifestu budou cesty na soubory, a přitom můžeš mít i prefix, kterej je jen na soubory.

**Comment by Halama** [comment]
jo to že leží na stejné urovni jako slices je taky jeden z problémů. Jenže o to kam se co nahrává se opět starají klienti. Tzn. pokud by se to měnilo museli bysme to říct. Takže to v tuhle chvíli asi moc nepomůže. A spíš bych postupoval k tomu odstranění manifestu.

**Comment by ondrejhlavacek** [comment]
Nojo vlastně. Nemůžu dohledat, jestli má Redshift nějaký omezení na počet souborů v manifestu pro import. Pokud nic takovýho nemá, tak by se na Redshift moh použít manifest a na Snowflake ho pomocí regexpu vyignorovat?

**Comment by ondrejhlavacek** [comment]
Nestačilo by k tomu https://github.com/keboola/php-db-import/issues/39#issuecomment-383028753 prostě ohlásit, že od nějaký chvíle se pro Snowflake načtou všechny soubory? Bude teda vypadat divně, že to bude jen Snowlake a ne Redshift. Ale pro Redshift by to taky šlo obejít.

**Comment by Halama** [comment]
!! `A process writes a new object to Amazon S3 and immediately lists keys within its bucket. Until the change is fully propagated, the object might not appear in the list.`

**Comment by Halama** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel

**Comment by Halama** [comment]
To imho znamená že manifesty musíme zachovat, protože to že to může skipnout nějaký slice je sakra nebezpečný.

**Comment by Halama** [comment]
Nebo se na to zeptat na supportu.

**Comment by ondrejhlavacek** [comment]
Na to jsme už někde naráželi, co? Vzhledem k tomu, co tady všude padá za slušný osery, tak bych asi začal tím, že budeme cyklovat po těch 1000 slicech na Snowflake.

**Comment by Halama** [comment]
Mám pocit že jo. A bojím se že u tohodle se prostě nedá říct počkáme 1sec a bude to ok:)
Souhlasím s tím abysme to teď udělali tím cyklováním a tohle můžeme zkoumat dál.

**Comment by Halama** [comment]
Assignuju si to a udělám to. Trochu s tím updatnu i tohle repo.

**Comment by ondrejhlavacek** [comment]
Tak to bude asi dost rychle co? Na update UI a dokumentace s tím limitem 1000 souborů zatím teda počkám, ať to zase za pár dní nemažu. Jediný, co bude deploy potřeba upravit, je default hodnota pro `limit` v https://github.com/keboola/aws-s3-extractor a probublat to přes weekly status

**Comment by Halama** [comment]
Jo mělo by to být rychlé. V tom S3 extractoru to chceš upravit jak?

**Comment by ondrejhlavacek** [comment]
Nastavil bych default na `0` (teď tam je `1000`) a napsal, že to může stahovat víc souborů.

**Comment by Halama** [comment]
Možná rovnou zkusím mrknout na nějaký json streaming parser... Ale uvidím nechci to zas komplikovat.

**Comment by Halama** [comment]
FILES
`a50a07d3-474f-4348-919f-4c2b3badecc0`
A zároven se tam předtím objevila tahle wtf věc `e5365fbb-b169-4b10-a776-e5475044ab5c`
![image](https://user-images.githubusercontent.com/903531/39360579-28ab86de-4a1f-11e8-981c-2d5091dfb09c.png)


![image](https://user-images.githubusercontent.com/903531/39360541-fcaa8f80-4a1e-11e8-85cb-ff522c2b7d19.png)

**Comment by Halama** [comment]
To samé 
![image](https://user-images.githubusercontent.com/903531/39361513-1e363fb0-4a23-11e8-91a1-3a46e097add3.png)

**Comment by Halama** [comment]
- 1. `284405a9-d333-4235-9c6c-333e1c2aa35d`
- 2. `06bbf70b-176b-472f-8640-0ad8a0e35922`
- 3. `3360b8fa-0ccd-4a64-a78d-b62008d2339d`
- 4. `37e4d096-7395-4115-a3fc-eceb4504aba9`

**Comment by Halama** [comment]
hmm,

> Of the three options for identifying/specifying data files to load from a stage, providing a discrete list of files is generally the fastest; however, the FILES parameter supports a maximum of 1,000 files, meaning a COPY command executed with the FILES parameter can only load up to 1,000 files.

https://docs.snowflake.net/manuals/user-guide/data-load-considerations-load.html

**Comment by Halama** [comment]
![image](https://user-images.githubusercontent.com/903531/39363887-2d8f3242-4a2c-11e8-9a73-b87822508773.png)

`'2c2149a2-f3ef-4a8a-924a-a21a3f142c88', '94b5b236-4b9d-48d5-b8db-eb0e538cf431', '149057f6-1bdc-4bd5-8a4f-8a2e3e3f0f1a', '301c7b68-0f73-44af-911e-51454c4d8d70'`

**Comment by Halama** [comment]
Stejný coomand který importuje jenom dva soubory tu describe query negeneruje `52861e29-2ea7-4cef-91a6-8366ceced9d7`. Ještě je divný že ta `DESCRIBE_QUERY` je jako první.

**Comment by Halama** [comment]
Z [tohodle](https://docs.snowflake.net/manuals/user-guide/data-load-considerations-load.html#options-for-selecting-staged-data-files) mi taky připadá že `COPY` command to neloaduje paralelně ale uživatel sám musí volat paralelně. Asi se zeptám na supportu.

**Comment by Halama** [comment]
Zkusím to ještě na souborech s 1M řádky.

**Comment by Halama** [comment]
Hodil jsem issue https://snowflakecommunity.force.com/s/case/5000Z00000yscSzQAI/data-loading-sliced-files kde se ptám proč tam jsou ty zdvojené query a jestli `COPY` loaduje paralelně.

**Comment by ondrejhlavacek** [comment]
Tohle mi teď přistálo v mailboxu

https://www.snowflake.net/how-to-load-terabytes-into-snowflake-speeds-feeds-and-techniques/

Maj tam 2000 souborů a regular

**Comment by Halama** [comment]
Testy s 1500x ~8MB uncompressed sliced file. Každý slice 1M řádků. 


# 1000 slices v jednom COPY commandu 

## X-small WH
`Time: 12.61 minutes, Memory: 182.04MB`
![image](https://user-images.githubusercontent.com/903531/39512276-ad975bf0-4df0-11e8-8233-d6f8319ca69f.png)

## Large WH
`Time: 8 minutes, Memory: 182.04MB`
![image](https://user-images.githubusercontent.com/903531/39512426-3dd5e344-4df1-11e8-9958-0348605b9069.png)

# PATH + PATTERN

## X-small WH
`Time: 6.05 minutes, Memory: 182.04MB`

![image](https://user-images.githubusercontent.com/903531/39513290-2a8058f8-4df4-11e8-8ff1-5023640dc12b.png)


## Large WH

`Time: 1.49 minutes, Memory: 182.04MB`

![image](https://user-images.githubusercontent.com/903531/39513022-3226cbf6-4df3-11e8-9b06-e1a84fea4699.png)

**Comment by Halama** [comment]
^ Cože teda úplně neodpovídá `Of the three options for identifying/specifying data files to load from a stage, providing a discrete list of files is generally the fastest;` https://docs.snowflake.net/manuals/user-guide/data-load-considerations-load.html#options-for-selecting-staged-data-files
Jinak to teda si vypadá že to jede paralelně.

**Comment by Halama** [comment]
Hmm, tak podle total execution time FILES i path časově sedí. Zřejmě se to ztratí v nějaké režii kolem.

![image](https://user-images.githubusercontent.com/903531/39513582-21c10432-4df5-11e8-9980-d78c21746f37.png)

https://kebooladev.snowflakecomputing.com/console#/monitoring/queries/detail?queryId=7545c63a-8575-4997-92b5-e91c5c38c571

**Comment by Halama** [comment]
Hádám že by ta režie mohla ale být konstantní. Zkusím to ještě na větších datech.

**Comment by Halama** [comment]
tvl, spustit ten load do s3 na micro instanci nebyl asi nejlepší nápad:(

**Comment by Halama** [comment]
Ještě to spouštím na `X-small` WH

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/php-db-import/issues/39#issuecomment-385905580

U Large WH + Copy command nevidím v žádný linkovaný query 1.5 G řádků, ale to je asi zbytečnej detail. Nemáš pro porovnání, kolik dělaj stejný objemy s manifestem?

**Comment by Halama** [comment]
vždyt tam jsou linkovaný query

**Comment by Halama** [comment]
A porovnání je tady https://github.com/keboola/php-db-import/issues/39#issuecomment-385903823

**Comment by Halama** [comment]
A ještě doběhlo srovnání 11G řádků na X-small

## FILES 1000 slices
![image](https://user-images.githubusercontent.com/903531/39538386-eca19d50-4e3c-11e8-8e74-1415531a19a7.png)

## PATH + PATTERN
![image](https://user-images.githubusercontent.com/903531/39538441-22d64402-4e3d-11e8-863b-d907efceb7b1.png)

**Comment by ondrejhlavacek** [comment]
jo, jasně! to je ten path + pattern slušně rychlejší teda!

**Comment by Halama** [comment]
no on by ten FILES správně měl být rychlejší ale je tam asi nějaká konstantní režie.

**Comment by ondrejhlavacek** [comment]
U těch 11G řádků se to pomalu začíná blížit k sobě.

**Comment by Halama** [comment]
WTF, teď tam mám ty zdvojený query zase. že by to bylo S3 v jiném regionu? mám totiž dvě instance testů, ty dnešní jsem pouštěl na ec2 v us-west-1 a tam to nedělalo. Teď jsem opět pustil moje lokální us-east-1. Jdu to ověřit.

![image](https://user-images.githubusercontent.com/903531/39539153-354fa1d0-4e3f-11e8-8577-764cd05665e8.png)

**Comment by Halama** [comment]
jinak to je na supportu ale zatím to jenom hodily na engineering. Na tu režii/výkon FILES vs. path se zeptám pak dál.

**Comment by Halama** [comment]
vypadá to že to tím je, z tou druhou S3 mi to nedělá ani z lokálu.

**Comment by Halama** [comment]
>  Hello Martin,
> 
> Please find the answers to your questions as follows:
> Answer 1: 
> DESCRIBE_QUERY is visible only in the case when using ODBC driver. It is kind of a handshake between client and snowflake service in which the driver receives information about the type of data it would be expecting from the service. The actual execution of the query does not take place in here. 
> 
> Answer 2: 
> You spun up x-small warehouse which started 8 threads in the background and these threads basically work in parallel. So when you issued COPY INTO statement, all those files were split among these threads to invoke parallelism. 
> 
> Let me know if you have any further questions. 
> 
> Regards,
> 
> Tushar Garg | Technical Support Engineer

**Comment by Halama** [comment]
> Hello Martin,
> 
> We received your comments. 
> 
> We try to hide the describe_query portion. It seems that hiding logic didn't seem to work in this case because it took a lot of time as there were a lot of files to process. 
> 
> Let me know if you have further questions.
