### ISSUE TITLE
QueryTimeout paramater took me all day ...

### ISSUE THREAD

**Issue by yustme** [keboola/php-db-import#58]
Tenhle parametr vůbec nedělá, to co by měl. Já bych ho odstranil a nechal ho zemřít hrozivou smrtí... :skull: :imp:
https://github.com/keboola/php-db-import/blob/cd99cfb57ae7a9e3928390d96000d82a12d009ba/src/Snowflake/Connection.php#L27

Místo toho, aby ustřihnul spojení po XX vteřinách, tak počká jak to dopadne a pokud se přesáhne "zhruba" dobu timeoutu, tak jenom napíše, že se to nestihlo, ale dotaz doběhne do konce.

**Comment by ErikZigo** [comment]
Ony obecne ty jejich DSN parametry jsou sranda a divna vec.

**Comment by yustme** [comment]
Problém byl, že jsem to testoval na funkci sleep, která se chová jinak než jiné query.
